source 'https://rubygems.org'

# Core
gem 'rails', '4.0.4'

# Database
group :development do
  gem 'sqlite3'
end
gem 'pg'

gem 'haml-rails'
gem 'markdown'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'

gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'turbolinks'

gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end

gem 'bcrypt', '~> 3.1.7'
gem 'unicorn'

# Dev tools
group :development, :test do
  gem 'debugger'
  gem 'pre-commit'
  gem 'rubocop'

  # test
  gem 'rspec'
end
